export const itemGroupMap: { [key: string]: string } = {
  '10': 'Fruits',
  '11': 'Vegetables',
  '12': 'Flowers',
  '13': 'Seed Bulbs Other',
  '20': 'Frozen Food',
  '30': 'Chilled Meats',
  '31': 'Chilled Dairy',
  '32': 'Chilled Cheese',
  '33': 'Chilled Delicatessen',
  '35': 'Butter',
  '36': 'Milk Related Products',
  '40': 'Ambient Meats',
  '41': 'Ambient Dairy',
  '42': 'Ambient Cheese',
  '43': 'Eggs',
  '44': 'Delicatessen/Spices/Mustard/Vinegar',
  '45': 'Oils/Fat/Margarine',
  '46': 'Coffee/Tea/Cocoa/Instant',
  '47': 'Biscuits/Foodstuffs/Breakfast Products',
  '48': 'Spreads',
  '49': 'Soup/Sauces/Dry mixes',
  '50': 'Tinned Fish',
  '51': 'Ready meals/Meat/Sausages tinned',
  '52': 'Fruit/Vegetables/Pickles tinned',
  '54': 'Baby Food',
  '60': 'Wine/Sparkling Wine',
  '61': 'Spirits/Liqueur',
  '62': 'Non Alcoholic drinks',
  '63': 'Beer/Beers mixes/Ciders',
  '70': 'Biscuits/Snacks',
  '71': 'Confectionery',
  '72': 'Bread/Bakery products/Cakes central',
  '73': 'Bread/Bakery decentral',
  '75': 'Bake-off',
  '77': 'OTC',
  '81': 'Pet Food',
  '82': 'Cosmetics',
  '83': 'Washing/Cleaning Products',
  '84': 'Paper/Foil/Hygiene',
  '85': 'Household goods/Hosiery',
  '86': 'Magazines',
  '90': 'Fresh Poultry',
  '91': 'Fresh Meat',
  '92': 'Fresh Fish',
  '98': 'Special Sale Food',
  '111': 'Media',
  '199': 'Packages',
  '201': "Women's Clothing",
  '202': "Men's Clothing",
  '203': "Children's Clothing",
  '204': "Young Children's Clothing",
  '205': 'Baby Clothing',
  '236': "Adult Sports Clothing",
  '237': "Children's Sports Clothing",
  '250': 'Accessories',
  '251': "Women's Shoes",
  '252': "Men's Shoes",
  '267': "Children's Shoes",
  '269': 'Shoe Accessories',
  '280': 'Home Textiles',
  '290': 'Home',
  '310': 'Kitchen Electrical Appliances',
  '311': 'Kitchen Household Goods',
  '320': 'Household',
  '321': 'Bathroom',
  '326': 'Body Care',
  '329': 'Health',
  '330': 'Entertainment Electronics',
  '333': 'Media',
  '334': 'Clocks/Weather Stations',
  '335': 'Gift Packaging/Cards',
  '338': 'Office Supplies',
  '345': 'Toys',
  '346': 'Arts/Crafts',
  '348': 'Fun & Sports/Games',
  '365': 'Animal World',
  '366': 'BBQ',
  '370': 'Gardening Tools',
  '371': 'Gardening Needs',
  '372': 'Cultivation/Planting',
  '373': 'Garden Furnishing/Decoration',
  '380': 'Cars',
  '381': 'Building/Renovation',
  '386': 'Workshop Machinery',
  '387': 'Workshop - Hardware',
  '388': 'Safety',
  '389': 'Heating/Cooling',
  '991': 'Kommissions-/Vermittlungsgeschaft',
  '995': 'Loyalty Aktionen',
  '996': 'Leergut(Pfand)',
  '997': 'Verbrauchsgüter',
  '998': 'Abschrift',
};
